# erzeugt Samstag, 04. Juli 2015 14:04 (C) 2015 von Leander Jedamus
# modifiziert Dienstag, 01. September 2015 13:46 von Leander Jedamus
# modifiziert Samstag, 15. August 2015 12:35 von Leander Jedamus
# modifiziert Mittwoch, 29. Juli 2015 13:28 von Leander Jedamus
# modifiziert Freitag, 17. Juli 2015 20:37 von Leander Jedamus
# modifiziert Dienstag, 14. Juli 2015 17:19 von Leander Jedamus
# modifiziert Mittwoch, 08. Juli 2015 15:20 von Leander Jedamus
# modifiziert Samstag, 04. Juli 2015 14:11 von Leander Jedamus

CWEAVE		= cweave
CTANGLE		= ctangle
NOWEAVE		= noweave
NOTANGLE	= notangle
SED		= sed

SEDCMD		= noweb2latex.sed
SEDTMP		= sed.tmp

NOWEAVE.latex	= $(NOWEAVE) -latex
NOWEB		= nw

define ctangle
$(RM) $@
$(CTANGLE) $<
endef

define cweave
$(RM) $@
$(CWEAVE) $<
endef

define notangle
$(RM) $@
$(NOTANGLE) -R$@ $< > $@
endef

define noweave
$(RM) $@
$(NOWEAVE.latex) $< > $@
endef

define sed
$(SED) -f $(SEDCMD) $@ > $(SEDTMP)
mv $(SEDTMP) $@
endef

%.c:		%.w
		$(ctangle)

%.tex:		%.w
		$(cweave)

%.c:		%.$(NOWEB)
		$(notangle)

%.h:		%.$(NOWEB)
		$(notangle)

%.cc:		%.$(NOWEB)
		$(notangle)

%.hh:		%.$(NOWEB)
		$(notangle)

%.tex:		%.$(NOWEB)
		$(noweave)
		$(sed)

# vim:ai sw=2 noexpandtab

